apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    environment: production
    app: redis
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: db
            operator: In
            values:
            - run
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: redis-with-pod-affinity
    image: k8s.gcr.io/pause:2.0
