apiVersion: v1
kind: Pod
metadata:
  name: web-with-redis
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - redis
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
