apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata:
 name: lab8pod
spec:
 containers:
 - name: animal
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   ports:
   - containerPort: 8080
